name: ci

on:
  release:
    types: ["published"]

env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.CONTAINER_NAME }}:${{ github.ref_name }}

jobs:
  dh_push:
    uses: yuri-kazliak/automation/.github/workflows/docker-hub-push.yml@main
    with:
      image_name: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.CONTAINER_NAME }}:${{ github.ref_name }}
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

    # runs-on: ubuntu-latest
    # if: ${{ github.ref_name }}
    # steps:
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ vars.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v3
    #   - name: Build and push
    #     uses: docker/build-push-action@v6
    #     with:
    #       push: true
    #       tags: ${{ env.IMAGE_NAME }}
  do_deploy:
    needs: dh_push
    uses: yuri-kazliak/automation/.github/workflows/digital-ocean-deploy.yml@main
    with:
      image_name: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.CONTAINER_NAME }}:${{ github.ref_name }}
      docker_container_name: ${{ vars.CONTAINER_NAME }}
      do_host: ${{ vars.DO_HOST }}
      do_username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      do_ssh_key: ${{ secrets.DO_SSHKEY }}

    # runs-on: ubuntu-latest
    # needs: build_and_push
    # if: ${{ github.ref_name }}

    # steps:
    #   - name: Checkout files
    #     uses: actions/checkout@v2
    #   - name: Deploy to Digital Ocean droplet via SSH action
    #     uses: appleboy/ssh-action@v1.0.3
    #     with:
    #       host: ${{ vars.DO_HOST }}
    #       username: ${{ vars.DOCKERHUB_USERNAME }}
    #       key: ${{ secrets.DO_SSHKEY }}
    #       envs: IMAGE_NAME
    #       script: |

    #         # Stop running container
    #         docker container stop $(echo ${{ vars.CONTAINER_NAME }})
    #         # Remove old container
    #         docker container rm -f $(echo ${{ vars.CONTAINER_NAME }})
    #         # Pull a new container
    #         docker image pull $(echo $IMAGE_NAME)
    #         # Run a new container from a new image
    #         docker run -d \
    #         --restart always \
    #         --name $(echo ${{ vars.CONTAINER_NAME }}) \
    #         -p 8018:8000 \
    #         $(echo $IMAGE_NAME)
